add the 'ascii-char' package
it defines the ASCII.Char module which is re-exported by the 'ascii'
package

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -90,16 +90,20 @@ install:
   - touch cabal.project
   - |
     echo "packages: ./ascii" >> cabal.project
+    echo "packages: ./ascii-char" >> cabal.project
     echo "packages: ./data-ascii" >> cabal.project
   - echo 'package ascii' >> cabal.project
+  - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
+  - echo 'package ascii-char' >> cabal.project
   - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
   - echo 'package data-ascii' >> cabal.project
   - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
   - |
-  - "for pkg in $($HCPKG list --simple-output); do echo $pkg | sed 's/-[^-]*$//' | (grep -vE -- '^(ascii|data-ascii)$' || true) | sed 's/^/constraints: /' | sed 's/$/ installed/' >> cabal.project.local; done"
+  - "for pkg in $($HCPKG list --simple-output); do echo $pkg | sed 's/-[^-]*$//' | (grep -vE -- '^(ascii|ascii-char|data-ascii)$' || true) | sed 's/^/constraints: /' | sed 's/$/ installed/' >> cabal.project.local; done"
   - cat cabal.project || true
   - cat cabal.project.local || true
   - if [ -f "./ascii/configure.ac" ]; then (cd "./ascii" && autoreconf -i); fi
+  - if [ -f "./ascii-char/configure.ac" ]; then (cd "./ascii-char" && autoreconf -i); fi
   - if [ -f "./data-ascii/configure.ac" ]; then (cd "./data-ascii" && autoreconf -i); fi
   - ${CABAL} v2-freeze $WITHCOMPILER ${TEST} ${BENCH}
   - "cat cabal.project.freeze | sed -E 's/^(constraints: *| *)//' | sed 's/any.//'"
@@ -116,19 +120,23 @@ script:
   - find . -maxdepth 1 -type f -name '*.tar.gz' -exec tar -xvf '{}' \;
   - find . -maxdepth 1 -type f -name '*.tar.gz' -exec rm       '{}' \;
   - PKGDIR_ascii="$(find . -maxdepth 1 -type d -regex '.*/ascii-[0-9.]*')"
+  - PKGDIR_ascii_char="$(find . -maxdepth 1 -type d -regex '.*/ascii-char-[0-9.]*')"
   - PKGDIR_data_ascii="$(find . -maxdepth 1 -type d -regex '.*/data-ascii-[0-9.]*')"
   # Generate cabal.project
   - rm -rf cabal.project cabal.project.local cabal.project.freeze
   - touch cabal.project
   - |
     echo "packages: ${PKGDIR_ascii}" >> cabal.project
+    echo "packages: ${PKGDIR_ascii_char}" >> cabal.project
     echo "packages: ${PKGDIR_data_ascii}" >> cabal.project
   - echo 'package ascii' >> cabal.project
+  - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
+  - echo 'package ascii-char' >> cabal.project
   - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
   - echo 'package data-ascii' >> cabal.project
   - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
   - |
-  - "for pkg in $($HCPKG list --simple-output); do echo $pkg | sed 's/-[^-]*$//' | (grep -vE -- '^(ascii|data-ascii)$' || true) | sed 's/^/constraints: /' | sed 's/$/ installed/' >> cabal.project.local; done"
+  - "for pkg in $($HCPKG list --simple-output); do echo $pkg | sed 's/-[^-]*$//' | (grep -vE -- '^(ascii|ascii-char|data-ascii)$' || true) | sed 's/^/constraints: /' | sed 's/$/ installed/' >> cabal.project.local; done"
   - cat cabal.project || true
   - cat cabal.project.local || true
   # Building...
@@ -139,6 +147,7 @@ script:
   - ${CABAL} v2-build $WITHCOMPILER ${TEST} ${BENCH} all
   # cabal check...
   - (cd ${PKGDIR_ascii} && ${CABAL} -vnormal check)
+  - (cd ${PKGDIR_ascii_char} && ${CABAL} -vnormal check)
   - (cd ${PKGDIR_data_ascii} && ${CABAL} -vnormal check)
   # haddock...
   - ${CABAL} v2-haddock $WITHCOMPILER --with-haddock $HADDOCK ${TEST} ${BENCH} all
