update package lists

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -92,8 +92,8 @@ install:
     echo "packages: ./ascii" >> cabal.project
     echo "packages: ./ascii-case" >> cabal.project
     echo "packages: ./ascii-char" >> cabal.project
-    echo "packages: ./ascii-char-superset" >> cabal.project
     echo "packages: ./ascii-group" >> cabal.project
+    echo "packages: ./ascii-superset" >> cabal.project
     echo "packages: ./data-ascii" >> cabal.project
   - echo 'package ascii' >> cabal.project
   - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
@@ -101,21 +101,21 @@ install:
   - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
   - echo 'package ascii-char' >> cabal.project
   - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
-  - echo 'package ascii-char-superset' >> cabal.project
-  - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
   - echo 'package ascii-group' >> cabal.project
+  - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
+  - echo 'package ascii-superset' >> cabal.project
   - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
   - echo 'package data-ascii' >> cabal.project
   - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
   - |
-  - "for pkg in $($HCPKG list --simple-output); do echo $pkg | sed 's/-[^-]*$//' | (grep -vE -- '^(ascii|ascii-case|ascii-char|ascii-char-superset|ascii-group|data-ascii)$' || true) | sed 's/^/constraints: /' | sed 's/$/ installed/' >> cabal.project.local; done"
+  - "for pkg in $($HCPKG list --simple-output); do echo $pkg | sed 's/-[^-]*$//' | (grep -vE -- '^(ascii|ascii-case|ascii-char|ascii-group|ascii-superset|data-ascii)$' || true) | sed 's/^/constraints: /' | sed 's/$/ installed/' >> cabal.project.local; done"
   - cat cabal.project || true
   - cat cabal.project.local || true
   - if [ -f "./ascii/configure.ac" ]; then (cd "./ascii" && autoreconf -i); fi
   - if [ -f "./ascii-case/configure.ac" ]; then (cd "./ascii-case" && autoreconf -i); fi
   - if [ -f "./ascii-char/configure.ac" ]; then (cd "./ascii-char" && autoreconf -i); fi
-  - if [ -f "./ascii-char-superset/configure.ac" ]; then (cd "./ascii-char-superset" && autoreconf -i); fi
   - if [ -f "./ascii-group/configure.ac" ]; then (cd "./ascii-group" && autoreconf -i); fi
+  - if [ -f "./ascii-superset/configure.ac" ]; then (cd "./ascii-superset" && autoreconf -i); fi
   - if [ -f "./data-ascii/configure.ac" ]; then (cd "./data-ascii" && autoreconf -i); fi
   - ${CABAL} v2-freeze $WITHCOMPILER ${TEST} ${BENCH}
   - "cat cabal.project.freeze | sed -E 's/^(constraints: *| *)//' | sed 's/any.//'"
@@ -134,8 +134,8 @@ script:
   - PKGDIR_ascii="$(find . -maxdepth 1 -type d -regex '.*/ascii-[0-9.]*')"
   - PKGDIR_ascii_case="$(find . -maxdepth 1 -type d -regex '.*/ascii-case-[0-9.]*')"
   - PKGDIR_ascii_char="$(find . -maxdepth 1 -type d -regex '.*/ascii-char-[0-9.]*')"
-  - PKGDIR_ascii_char_superset="$(find . -maxdepth 1 -type d -regex '.*/ascii-char-superset-[0-9.]*')"
   - PKGDIR_ascii_group="$(find . -maxdepth 1 -type d -regex '.*/ascii-group-[0-9.]*')"
+  - PKGDIR_ascii_superset="$(find . -maxdepth 1 -type d -regex '.*/ascii-superset-[0-9.]*')"
   - PKGDIR_data_ascii="$(find . -maxdepth 1 -type d -regex '.*/data-ascii-[0-9.]*')"
   # Generate cabal.project
   - rm -rf cabal.project cabal.project.local cabal.project.freeze
@@ -144,8 +144,8 @@ script:
     echo "packages: ${PKGDIR_ascii}" >> cabal.project
     echo "packages: ${PKGDIR_ascii_case}" >> cabal.project
     echo "packages: ${PKGDIR_ascii_char}" >> cabal.project
-    echo "packages: ${PKGDIR_ascii_char_superset}" >> cabal.project
     echo "packages: ${PKGDIR_ascii_group}" >> cabal.project
+    echo "packages: ${PKGDIR_ascii_superset}" >> cabal.project
     echo "packages: ${PKGDIR_data_ascii}" >> cabal.project
   - echo 'package ascii' >> cabal.project
   - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
@@ -153,14 +153,14 @@ script:
   - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
   - echo 'package ascii-char' >> cabal.project
   - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
-  - echo 'package ascii-char-superset' >> cabal.project
-  - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
   - echo 'package ascii-group' >> cabal.project
+  - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
+  - echo 'package ascii-superset' >> cabal.project
   - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
   - echo 'package data-ascii' >> cabal.project
   - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
   - |
-  - "for pkg in $($HCPKG list --simple-output); do echo $pkg | sed 's/-[^-]*$//' | (grep -vE -- '^(ascii|ascii-case|ascii-char|ascii-char-superset|ascii-group|data-ascii)$' || true) | sed 's/^/constraints: /' | sed 's/$/ installed/' >> cabal.project.local; done"
+  - "for pkg in $($HCPKG list --simple-output); do echo $pkg | sed 's/-[^-]*$//' | (grep -vE -- '^(ascii|ascii-case|ascii-char|ascii-group|ascii-superset|data-ascii)$' || true) | sed 's/^/constraints: /' | sed 's/$/ installed/' >> cabal.project.local; done"
   - cat cabal.project || true
   - cat cabal.project.local || true
   # Building...
@@ -173,8 +173,8 @@ script:
   - (cd ${PKGDIR_ascii} && ${CABAL} -vnormal check)
   - (cd ${PKGDIR_ascii_case} && ${CABAL} -vnormal check)
   - (cd ${PKGDIR_ascii_char} && ${CABAL} -vnormal check)
-  - (cd ${PKGDIR_ascii_char_superset} && ${CABAL} -vnormal check)
   - (cd ${PKGDIR_ascii_group} && ${CABAL} -vnormal check)
+  - (cd ${PKGDIR_ascii_superset} && ${CABAL} -vnormal check)
   - (cd ${PKGDIR_data_ascii} && ${CABAL} -vnormal check)
   # haddock...
   - ${CABAL} v2-haddock $WITHCOMPILER --with-haddock $HADDOCK ${TEST} ${BENCH} all
